serviceName: "task-management"

restServer:
  port: 8080

mongoDB:
  uri: "mongodb://localhost:27017"
  port: 27017
  username: "root"
  password: "example"
  database: "task_management"

grpcServer:
  port: 50051
  maxRecvMsgSize: 4
  maxSendMsgSize: 4
  useReflection: true

grpcClient:
  notificationService:
    name: "notification"
    host: "localhost"
    port: 50052
    maxSendMsgSize: 4
    maxRecvMsgSize: 4
