serviceName: "notification"

grpcServer:
  port: 50052
  maxRecvMsgSize: 4
  maxSendMsgSize: 4
  useReflection: true

grpcClient:
  taskManagementService:
    name: "task-management"
    host: "localhost"
    port: 50051
    maxSendMsgSize: 4
    maxRecvMsgSize: 4
