services:
  api:
    build:
      context: ./docker/
      dockerfile: go-air.Dockerfile
    restart: on-failure
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
    networks:
      - task-nexus-network
  mongo:
    image: mongo:8.0.3-noble
    restart: on-failure
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - task-nexus-network
    volumes:
      - task-nexus-mongo-vol-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
volumes:
  task-nexus-mongo-vol-db:
    driver: local
networks:
  task-nexus-network:
    driver: bridge